language: csharp
os: linux
dist: trusty
sudo: false
dotnet: 2.1.403
mono: none

# cache:
#   yarn: true

before_script:
  - nvm install 10.15.0
  - nvm use 10.15.0
  # # Update npm
  # - npm install -g npm

script:
  - npm install && npm test
